declare const fs: any;
declare const path: any;
declare const STUB_HEADER = "// This file was auto-generated by the card stub generator.\n// Card effects were implemented by an agent.\n// If you have any questions or feedback, reach out to @C4 in the discord.\n";
declare const TYPE_TO_SHORT: Record<string, string>;
declare function typeShort(type: string): string;
declare function getStage(subtypes: string[]): string;
declare function getTrainerType(subtypes: string[]): string;
declare function getPowerType(type: string): string;
declare function getUseWhenInPlay(type: string): boolean;
declare const GENERIC_RULES: string[];
declare function filterGenericRules(rules: string[]): string[];
declare function convertEnergyNames(text: string): string;
declare function parseDamage(dmgStr: string): {
    damage: number;
    damageCalculation?: string;
};
declare function parseResistanceValue(value: string): number;
declare function cardNeedsReduceEffect(card: any): boolean;
declare function cardsAreIdentical(a: any, b: any): boolean;
interface CrossSetEntry {
    className: string;
    setDir: string;
    fileName: string;
    hasReduceEffect: boolean;
    attackNames: string[];
    abilityNames: string[];
}
declare function buildCrossSetIndex(setsDir: string, currentSetDir: string): Map<string, CrossSetEntry[]>;
declare function generatePokemonStub(card: any, className: string, setCode: string, needsReduceEffect: boolean, fullName: string): string;
declare function generateTrainerStub(card: any, className: string, setCode: string, fullName: string): string;
declare function generateEnergyStub(card: any, className: string, setCode: string, fullName: string): string;
interface OtherPrintEntry {
    className: string;
    sourceClassName: string;
    importPath: string;
    setCode: string;
    setNumber: string;
    fullName: string;
    importAlias?: string;
}
declare function generateOtherPrintsEntry(entry: OtherPrintEntry): string;
declare function generateIndex(setDir: string, setDirName: string, allCardFiles: {
    className: string;
    fileName: string;
    category: string;
}[], otherPrintClasses: string[]): string;
